---
linters:
  disable-all: true
  enable:
    - asciicheck
    - bidichk
    - durationcheck
    - errname
    - exportloopref
    - gocyclo
    - godot
    - gofmt
    - gosec
    - gosimple
    - ineffassign
    - makezero
    - misspell
    - prealloc
    - staticcheck
    - tenv
    - typecheck
    - unconvert
    - unused
    - wastedassign
    - whitespace

linters-settings:
  misspell:
    locale: US
