---
linters:
  disable-all: true
  enable:
    - asciicheck
    - bidichk
    - durationcheck
    - errname
    - exportloopref
    - gocyclo
    - godot
    - gofmt
    - gosec
    - gosimple
    - ineffassign
    - makezero
    - misspell
    - prealloc
    - staticcheck
    - tenv
    - typecheck
    - unconvert
    - unused
    - wastedassign
    - whitespace

linters-settings:
  misspell:
    locale: US

issues:
  exclude-rules:
    # We'll replace references to io/ioutil later. Until then we don't
    # want to hear about it.
    - linters:
        - staticcheck
      text: 'SA1019: "io/ioutil" has been deprecated'
