// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"context"
	"sync"

	"github.com/magnusbaeck/logstash-filter-verifier/v2/internal/daemon/controller"
)

// Ensure, that InstanceMock does implement controller.Instance.
// If this is not the case, regenerate this file with moq.
var _ controller.Instance = &InstanceMock{}

// InstanceMock is a mock implementation of controller.Instance.
//
// 	func TestSomethingThatUsesInstance(t *testing.T) {
//
// 		// make and configure a mocked controller.Instance
// 		mockedInstance := &InstanceMock{
// 			ConfigReloadFunc: func() error {
// 				panic("mock out the ConfigReload method")
// 			},
// 			StartFunc: func(ctx context.Context, controllerMoqParam *controller.Controller, workdir string) error {
// 				panic("mock out the Start method")
// 			},
// 		}
//
// 		// use mockedInstance in code that requires controller.Instance
// 		// and then make assertions.
//
// 	}
type InstanceMock struct {
	// ConfigReloadFunc mocks the ConfigReload method.
	ConfigReloadFunc func() error

	// StartFunc mocks the Start method.
	StartFunc func(ctx context.Context, controllerMoqParam *controller.Controller, workdir string) error

	// calls tracks calls to the methods.
	calls struct {
		// ConfigReload holds details about calls to the ConfigReload method.
		ConfigReload []struct {
		}
		// Start holds details about calls to the Start method.
		Start []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ControllerMoqParam is the controllerMoqParam argument value.
			ControllerMoqParam *controller.Controller
			// Workdir is the workdir argument value.
			Workdir string
		}
	}
	lockConfigReload sync.RWMutex
	lockStart        sync.RWMutex
}

// ConfigReload calls ConfigReloadFunc.
func (mock *InstanceMock) ConfigReload() error {
	if mock.ConfigReloadFunc == nil {
		panic("InstanceMock.ConfigReloadFunc: method is nil but Instance.ConfigReload was just called")
	}
	callInfo := struct {
	}{}
	mock.lockConfigReload.Lock()
	mock.calls.ConfigReload = append(mock.calls.ConfigReload, callInfo)
	mock.lockConfigReload.Unlock()
	return mock.ConfigReloadFunc()
}

// ConfigReloadCalls gets all the calls that were made to ConfigReload.
// Check the length with:
//     len(mockedInstance.ConfigReloadCalls())
func (mock *InstanceMock) ConfigReloadCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockConfigReload.RLock()
	calls = mock.calls.ConfigReload
	mock.lockConfigReload.RUnlock()
	return calls
}

// Start calls StartFunc.
func (mock *InstanceMock) Start(ctx context.Context, controllerMoqParam *controller.Controller, workdir string) error {
	if mock.StartFunc == nil {
		panic("InstanceMock.StartFunc: method is nil but Instance.Start was just called")
	}
	callInfo := struct {
		Ctx                context.Context
		ControllerMoqParam *controller.Controller
		Workdir            string
	}{
		Ctx:                ctx,
		ControllerMoqParam: controllerMoqParam,
		Workdir:            workdir,
	}
	mock.lockStart.Lock()
	mock.calls.Start = append(mock.calls.Start, callInfo)
	mock.lockStart.Unlock()
	return mock.StartFunc(ctx, controllerMoqParam, workdir)
}

// StartCalls gets all the calls that were made to Start.
// Check the length with:
//     len(mockedInstance.StartCalls())
func (mock *InstanceMock) StartCalls() []struct {
	Ctx                context.Context
	ControllerMoqParam *controller.Controller
	Workdir            string
} {
	var calls []struct {
		Ctx                context.Context
		ControllerMoqParam *controller.Controller
		Workdir            string
	}
	mock.lockStart.RLock()
	calls = mock.calls.Start
	mock.lockStart.RUnlock()
	return calls
}
