name: test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: "1.16.8"

    - name: Install APT-based build dependencies
      run: >
        sudo apt-get update &&
        sudo apt-get install make protobuf-compiler

    - name: Run static analysis
      run: make check checktidy

    - name: Run tests
      run: make test
